### PR TITLE
Download assets before build

### PR DESCRIPTION
**Pull request by lox**
To ensure that builds use the lastest versions of releases this downloads assets
first and copies them into the Docker build, ensuring layer cache doesn't miss subsequent versions.

### CODE REVIEW

**Comment by toolmantim** [comment]
Noice! :+1:

**Comment by lox** [comment]
I'm by no means proud of that `download.sh` :/ 

Think it's a bad idea to avoid using the bash installer you guys provide @toolmantim?

**Comment by toolmantim** [comment]
Hmm not sure. @keithpitt?

**Comment by lox** [comment]
It looked to me like most of the stuff in there was to deal with people installing into different environments. Into a docker container is a pretty controlled install.

**Comment by keithpitt** [comment]
I think it's fine using the installer - that's what it's there for!

**Comment by keithpitt** [comment]
(And I have no plan on getting rid of it any time soon)

**Comment by lox** [comment]
Sorry, we meant is it ok to NOT use it?

**Comment by lox** [comment]
This script does the look up from https://buildkite.com/agent/releases/latest directly.

**Comment by keithpitt** [comment]
Oh right! Yeah, that's cool too! :) Sorry, I totally misread that. Do what evs :)

**Pull request merged**
