### PR TITLE
Dind tagged docker versions

### PR DESCRIPTION
**Pull request by lox**
This adds specific versions of the dind agent with specific versions of Docker, as otherwise it's just the latest upstream image: https://github.com/jpetazzo/dind/blob/master/Dockerfile#L13

This will correspond to tags: 
- `dind` - whatever the latest is
- `dind-X.X` - whatever the most recent minor release of X.X is 
- `dind-X.X.X` - a specific version

### CODE REVIEW

**Comment by lox** [comment]
@toolmantim Thoughts?

**Comment by lox** [comment]
Test builds here if anyone wants to try them https://registry.hub.docker.com/u/lox24/buildkite-agent/

**Comment by lox** [comment]
This is what my automated build setup on docker hub looks like:

http://lachlan.me/s/5fdrp.png

**Comment by toolmantim** [comment]
Ah yeah, I definitely see how this is needed. I was wondering how to best to set this up when you want parity with the host docker. :+1: Will set this up and merge it in.

**Comment by toolmantim** [comment]
Also perhaps the DIND images themselves should have this? Is there any reason we couldn't send a PR to them, and then just depend on `FROM jpetazzo/dind-1.7` etc?

**Comment by lox** [comment]
Yup, that sounds really sensible @toolmantim. Will do that.

**Comment by toolmantim** [comment]
I just realised though, we can easily update this when the upstream images have been updated too. In the mean time we can easily just ship these… it's not like the tags will change?

**Comment by toolmantim** [comment]
I've merged these and have updated docker hub automated builds config. They're building now :+1: Thanks Lach!

**Pull request merged**
