### PR TITLE
Add docker 1.10 images

### PR DESCRIPTION
**Pull request by lox**
This adds the latest docker/compose to both alpine and ubuntu images.

### CODE REVIEW

**Comment by lox** [comment]
Actually, the only thing that dawned on me is that the alpine image doesn't have tags for different docker versions. Not sure if this is a big deal.

**Comment by toolmantim** [comment]
@lox what's the deal with not having diff Docker versions?

**Comment by lox** [comment]
@toolmantim we should probably add a tag for the alpine image for specific docker versions. The current one has 1.9.1.

**Comment by gittycat** [comment]
Docker is now at 1.10.1. Might as well skip 1.10.0
I also agree with specifying the alpine version (alpine:3.3) for 1.10.1.

**Comment by lox** [comment]
Agreed!

**Comment by lox** [comment]
Btw, I was talking about adding a tag for the alpine+docker version, so like we have `buildkite/agent:ubuntu-docker-1.9`, we'd have `buildkite/agent:alpine-docker-1.9` (for stable)

**Comment by lox** [comment]
But yeah, let's refer to `alpine:3.3` specifically too. I think adding a buildkite agent tag for it is probably overkill though.

**Comment by toolmantim** [comment]
👍👍

**Comment by lox** [comment]
Discovered a minor bug that causes 1.10 to not be installed on the alpine image. Testing.

**Comment by lox** [comment]
Ok, fixed.

**Comment by lox** [comment]
Merge at your leisure @toolmantim

**Pull request merged**
